/**
 * Generates packages/shared/content/prompts/mature-curated-games.json
 * Run: node --import tsx scripts/generate-mature-curated-games.mts
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  expandImpostorItems,
  generateCreativePools,
} from "./mature-creative-generators.ts";

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "../packages/shared/content/prompts/mature-curated-games.json",
);

const factCheck = [
  { prompt: "The first electric vibrator was sold as a cure for", truth: "female hysteria" },
  { prompt: "The world's oldest profession is often called", truth: "prostitution" },
  { prompt: "A merkin is a fake", truth: "pubic wig" },
  { prompt: "The G-spot is named after researcher", truth: "Ernst Gräfenberg" },
  { prompt: "The Kama Sutra originated in ancient", truth: "India" },
  { prompt: "The first condoms were reportedly made from", truth: "animal intestines" },
  { prompt: "Blue balls is slang for", truth: "testicular aching from arousal" },
  { prompt: "A glory hole is associated with", truth: "anonymous sexual contact" },
  { prompt: "Burlesque shows often feature", truth: "striptease" },
  { prompt: "The prostate is sometimes called the male", truth: "G-spot" },
  { prompt: "A cock ring is worn to restrict", truth: "blood flow" },
  { prompt: "Fellatio is another word for", truth: "oral sex on a penis" },
  { prompt: "Cunnilingus is oral stimulation of the", truth: "vulva" },
  { prompt: "A strap-on dildo is often used for", truth: "pegging" },
  { prompt: "The clitoris has roughly twice as many nerve endings as the", truth: "penis" },
  { prompt: "Kinsey's famous reports studied human", truth: "sexuality" },
  { prompt: "The term MILF became popular after a", truth: "teen comedy film" },
  { prompt: "A safeword is used in BDSM to mean", truth: "stop immediately" },
  { prompt: "The penis bone in many mammals is called the", truth: "baculum" },
  { prompt: "Foreplay is meant to increase", truth: "arousal" },
  { prompt: "A threesome involves", truth: "three people" },
  { prompt: "An orgy typically involves", truth: "group sex" },
  { prompt: "A dominatrix is a woman who takes a", truth: "dominant role" },
  { prompt: "Submissive partners in BDSM are often called", truth: "subs" },
  { prompt: "A ball gag is a", truth: "BDSM mouth restraint" },
  { prompt: "Nipple clamps are used for", truth: "sensation play" },
  { prompt: "Lube reduces friction during", truth: "sex" },
  { prompt: "The missionary position is named for its association with", truth: "colonial missionaries" },
  { prompt: "Doggy style is a", truth: "rear-entry sex position" },
  { prompt: "Cowgirl position has the receptive partner on", truth: "top" },
  { prompt: "A one night stand is sex with", truth: "no follow-up relationship" },
  { prompt: "Friends with benefits combine friendship and", truth: "casual sex" },
  { prompt: "Sexting means sending", truth: "sexual messages" },
  { prompt: "OnlyFans creators often sell", truth: "adult content" },
  { prompt: "A lap dance is performed while the customer is", truth: "seated" },
  { prompt: "A strip club is where performers do", truth: "striptease" },
  { prompt: "The red light district is known for", truth: "sex work" },
  { prompt: "A brothel is a place for", truth: "paid sex" },
  { prompt: "An escort service arranges", truth: "paid companionship" },
  { prompt: "Pornography is media intended to cause", truth: "sexual arousal" },
  { prompt: "Playboy magazine was founded by", truth: "Hugh Hefner" },
  { prompt: "Hustler magazine was founded by", truth: "Larry Flynt" },
  { prompt: "The adult film industry center in California is the", truth: "San Fernando Valley" },
  { prompt: "A fluffer on set helps performers stay", truth: "aroused" },
  { prompt: "A money shot in porn refers to", truth: "ejaculation on camera" },
  { prompt: "Voyeurism is arousal from", truth: "watching others" },
  { prompt: "Exhibitionism is arousal from", truth: "being watched" },
  { prompt: "A foot fetish is sexual interest in", truth: "feet" },
  { prompt: "Bondage involves restricting a partner's", truth: "movement" },
  { prompt: "A blindfold is used to heighten", truth: "other senses" },
  { prompt: "Roleplay in bed might involve", truth: "fantasy characters" },
  { prompt: "An aphrodisiac is something believed to increase", truth: "libido" },
  { prompt: "Morning wood is a common", truth: "nocturnal erection" },
  { prompt: "Wet dreams are orgasms during", truth: "sleep" },
  { prompt: "Circumcision removes the", truth: "foreskin" },
  { prompt: "The labia are part of the", truth: "vulva" },
  { prompt: "Testicles produce", truth: "sperm" },
  { prompt: "The scrotum holds the", truth: "testicles" },
  { prompt: "Anal sex involves the", truth: "anus" },
  { prompt: "A butt plug is inserted into the", truth: "anus" },
  { prompt: "A fleshlight is a brand of", truth: "male sex toy" },
  { prompt: "A vibrator is a device for", truth: "sexual stimulation" },
  { prompt: "Lingerie is", truth: "sexy underwear" },
  { prompt: "A thong leaves the", truth: "buttocks exposed" },
  { prompt: "Skinny dipping means swimming", truth: "naked" },
  { prompt: "A walk of shame is leaving after", truth: "a hookup" },
  { prompt: "Dirty talk is", truth: "erotic speech during sex" },
  { prompt: "A hookup is a", truth: "casual sexual encounter" },
  { prompt: "An affair is sex outside a", truth: "committed relationship" },
  { prompt: "Polyamory means having multiple", truth: "romantic partners" },
  { prompt: "Swingers are couples who swap", truth: "sexual partners" },
  { prompt: "A sugar daddy provides gifts for", truth: "companionship" },
  { prompt: "A cam girl performs on", truth: "webcam" },
  { prompt: "Hentai is", truth: "animated pornography" },
  { prompt: "Rule 34 of the internet says if it exists there is", truth: "porn of it" },
  { prompt: "The banana hammock is slang for a", truth: "men's thong" },
  { prompt: "A three-breasted woman appeared in the film", truth: "Total Recall" },
  { prompt: "Fifty Shades of Grey popularized", truth: "BDSM romance" },
  { prompt: "The Joy of Sex was a famous", truth: "sex manual" },
  { prompt: "A rimjob is oral contact with the", truth: "anus" },
  { prompt: "Blue movie is old slang for", truth: "pornographic film" },
  { prompt: "Streaking is running", truth: "naked in public" },
  { prompt: "A merkin was used in films to cover", truth: "genitals" },
  { prompt: "The clitoris is primarily for", truth: "pleasure" },
  { prompt: "Foreskin protects the sensitive", truth: "glans" },
  { prompt: "An orgasm is a peak of", truth: "sexual pleasure" },
  { prompt: "Premature ejaculation means coming", truth: "too quickly" },
  { prompt: "Erectile dysfunction is difficulty getting an", truth: "erection" },
  { prompt: "Aphrodisiac oysters are mostly", truth: "a myth" },
  { prompt: "The penis becomes erect when blood fills the", truth: "corpora cavernosa" },
  { prompt: "A dental dam is a barrier for", truth: "oral sex" },
  { prompt: "A condom is a barrier method for", truth: "safer sex" },
  { prompt: "The pill is a form of", truth: "birth control" },
  { prompt: "An IUD is inserted into the", truth: "uterus" },
  { prompt: "A vasectomy blocks", truth: "sperm delivery" },
  { prompt: "The morning-after pill prevents", truth: "pregnancy after sex" },
  { prompt: "STI stands for sexually transmitted", truth: "infection" },
  { prompt: "Herpes is a common", truth: "sexually transmitted infection" },
  { prompt: "Chlamydia is often called a silent", truth: "STI" },
  { prompt: "HPV can cause", truth: "cervical cancer" },
  { prompt: "PrEP helps prevent", truth: "HIV transmission" },
  { prompt: "A glory hole wall has a", truth: "hole for anonymous sex" },
  { prompt: "Pole dancing for fitness uses a", truth: "stripper pole" },
  { prompt: "Pasties cover the", truth: "nipples" },
  { prompt: "A cuckold fantasy involves a partner with", truth: "someone else" },
  { prompt: "Aftercare in kink means comforting a partner after", truth: "intense play" },
  { prompt: "A flogger is a", truth: "whip with tails" },
  { prompt: "Handcuffs in the bedroom are for", truth: "restraint play" },
  { prompt: "Spanking for pleasure is a form of", truth: "impact play" },
  { prompt: "A safe word like red means", truth: "stop now" },
  { prompt: "Edging means delaying", truth: "orgasm" },
  { prompt: "A threesome app bio might mention being", truth: "open-minded" },
  { prompt: "OnlyFans revolutionized", truth: "creator-owned adult content" },
  { prompt: "The adult industry calls explicit scenes", truth: "hardcore" },
  { prompt: "A stripper pole spin is called a", truth: "invert" },
  { prompt: "Burlesque pasties are often", truth: "rhinestone-covered" },
  { prompt: "A merkin in Total Recall was", truth: "three-breasted cosplay" },
  { prompt: "The Kama Sutra lists many", truth: "sex positions" },
  { prompt: "Tantric sex focuses on prolonged", truth: "intimacy" },
  { prompt: "A prostate massage can be done through the", truth: "anus" },
  { prompt: "The perineum is between the genitals and", truth: "anus" },
  { prompt: "A cock ring should not be worn longer than", truth: "30 minutes" },
  { prompt: "Nipple play can trigger", truth: "arousal" },
  { prompt: "A butt plug has a flared", truth: "base for safety" },
  { prompt: "Lube is essential for comfortable", truth: "anal sex" },
  { prompt: "A dildo is a", truth: "penis-shaped sex toy" },
  { prompt: "A rabbit vibrator stimulates the clitoris and", truth: "G-spot" },
  { prompt: "A wand massager became famous as a", truth: "clitoral vibrator" },
  { prompt: "Fleshlight is a brand of", truth: "penis sleeve toy" },
  { prompt: "A strap-on harness holds a", truth: "dildo" },
  { prompt: "Pegging is when a woman anally penetrates a man with a", truth: "strap-on" },
  { prompt: "A glory hole is controversial because of", truth: "anonymous risk" },
  { prompt: "Red light windows are associated with", truth: "legal prostitution" },
  { prompt: "Amsterdam's red light district is in", truth: "De Wallen" },
  { prompt: "The world's oldest profession debate centers on", truth: "sex work" },
  { prompt: "A porn set has an intimacy", truth: "coordinator" },
  { prompt: "Bukkake is a genre involving multiple", truth: "ejaculations" },
  { prompt: "Hentai is Japanese", truth: "animated porn" },
  { prompt: "Rule 34 means there is porn of", truth: "everything" },
  { prompt: "A sugar baby arrangement trades companionship for", truth: "gifts or money" },
  { prompt: "A cam site tip menu might list", truth: "custom shows" },
  { prompt: "OnlyFans allows creators to sell", truth: "paywalled nudes" },
  { prompt: "A thirst trap is a photo meant to attract", truth: "sexual attention" },
  { prompt: "Sexting nudes can be", truth: "legally risky for minors" },
  { prompt: "Revenge porn is sharing intimate images", truth: "without consent" },
  { prompt: "A hookup culture emphasizes", truth: "casual sex" },
  { prompt: "Friends with benefits avoid", truth: "romantic commitment" },
  { prompt: "A one night stand rarely includes", truth: "breakfast plans" },
  { prompt: "The walk of shame often involves", truth: "yesterday's outfit" },
  { prompt: "Skinny dipping is illegal in many", truth: "public places" },
  { prompt: "Streaking at sports events is a", truth: "naked prank" },
  { prompt: "A merkin hides lack of", truth: "pubic hair on set" },
  { prompt: "Pasties let burlesque dancers show skin without revealing", truth: "nipples" },
  { prompt: "A banana hammock is a revealing", truth: "men's swimsuit" },
  { prompt: "Three-breasted woman cosplay references", truth: "Total Recall" },
  { prompt: "Stripper pole classes teach", truth: "pole fitness" },
  { prompt: "Lap dance rules often forbid", truth: "touching" },
  { prompt: "A bachelorette party might hire a", truth: "stripper" },
  { prompt: "A bachelor party might visit a", truth: "strip club" },
  { prompt: "Dirty dancing means dancing", truth: "suggestively close" },
  { prompt: "Grinding on the dance floor is", truth: "frotteurism-adjacent" },
  { prompt: "A horny group chat gets archived when", truth: "someone screenshots it" },
  { prompt: "An affair text sent to the wrong person causes", truth: "panic" },
  { prompt: "Sexting autocorrect has ruined many", truth: "relationships" },
  { prompt: "A secret OnlyFans discovered by family leads to", truth: "awkward holidays" },
  { prompt: "A workplace hookup risks", truth: "HR meetings" },
  { prompt: "A hotel key card left at breakfast signals", truth: "a hookup" },
  { prompt: "The spare toothbrush test reveals", truth: "overnight guests" },
  { prompt: "A mysterious bruise after a hookup needs", truth: "a cover story" },
  { prompt: "Venmo at 4am often means", truth: "drinks or regret" },
  { prompt: "A screenshot leak ends", truth: "situationships" },
  { prompt: "The group chat recap reconstructs", truth: "last night's sins" },
];

const quiz: Array<{ question: string; choices: string[]; correct: number }> = [
  ["What is the primary purpose of the clitoris?", ["Pleasure", "Reproduction", "Urination", "Hormone storage"], 0],
  ["Which magazine did Hugh Hefner found?", ["Playboy", "Hustler", "Penthouse", "Maxim"], 0],
  ["What does BDSM stand for?", ["Bondage discipline dominance submission", "Basic dating safety manual", "Bedroom decor style mode", "Bold dance show music"], 0],
  ["A merkin is a fake what?", ["Pubic wig", "Breast implant", "Nose prosthetic", "Tongue ring"], 0],
  ["Fellatio refers to oral sex on the", ["Penis", "Vulva", "Anus", "Breasts"], 0],
  ["Cunnilingus refers to oral sex on the", ["Vulva", "Penis", "Anus", "Nipples"], 0],
  ["The G-spot is named after Ernst", ["Gräfenberg", "Gutenberg", "Gandhi", "Galileo"], 0],
  ["What is pegging?", ["Woman anally penetrating man with strap-on", "A fishing technique", "A dance move", "A card game"], 0],
  ["Kinsey is famous for studying human", ["Sexuality", "Geology", "Bird migration", "Ocean currents"], 0],
  ["A safeword in kink means", ["Stop immediately", "Go harder", "Switch partners", "Take a photo"], 0],
  ["The prostate is sometimes called the male", ["G-spot", "L-spot", "T-zone", "Q-tip"], 0],
  ["What is a fluffer's job on an adult set?", ["Help performers stay aroused", "Clean the set", "Cook lunch", "Edit footage"], 0],
  ["Which city is famous for its red light district De Wallen?", ["Amsterdam", "Paris", "Rome", "Berlin"], 0],
  ["A cock ring restricts blood flow to maintain", ["Erection", "Hair growth", "Appetite", "Balance"], 0],
  ["The Kama Sutra originated in", ["India", "Greece", "Egypt", "China"], 0],
  ["What is a dental dam used for?", ["Barrier during oral sex", "Teeth whitening", "Jaw surgery", "Snoring"], 0],
  ["Hentai is a genre of", ["Animated pornography", "Horror films", "Cooking shows", "Sports anime"], 0],
  ["A butt plug is designed for insertion in the", ["Anus", "Ear", "Nose", "Mouth"], 0],
  ["OnlyFans is best known for", ["Creator-subscriber adult content", "Food delivery", "Ride sharing", "Cloud storage"], 0],
  ["Burlesque performances often include", ["Striptease", "Opera singing", "Ballet only", "Magic tricks"], 0],
  ["A glory hole is associated with", ["Anonymous sexual contact", "Glory hunting", "Church windows", "Skate tricks"], 0],
  ["What does MILF stand for in pop culture?", ["Mother I'd like to flirt with", "Movie in late February", "Milk industry logistics firm", "Major indoor lacrosse federation"], 0],
  ["The first condoms were historically made from", ["Animal intestines", "Rubber tires", "Glass tubes", "Paper mache"], 0],
  ["A dominatrix typically takes a", ["Dominant role", "Submissive role", "Neutral role", "Spectator role"], 0],
  ["Voyeurism involves arousal from", ["Watching others", "Being watched", "Cooking", "Running"], 0],
  ["Exhibitionism involves arousal from", ["Being watched", "Watching others", "Sleeping", "Reading"], 0],
  ["A lap dance is usually performed while the customer is", ["Seated", "Standing on a ladder", "Swimming", "Driving"], 0],
  ["The missionary position is named partly after", ["Colonial missionaries", "Mission control", "Mission statements", "Mission Impossible"], 0],
  ["Doggy style is a", ["Rear-entry position", "Yoga warm-up", "Dog training method", "Card game"], 0],
  ["A threesome involves how many people?", ["Three", "Two", "Four", "One"], 0],
  ["An orgy typically involves", ["Group sex", "Solo meditation", "Team sports", "Book club"], 0],
  ["Sexting means sending", ["Sexual messages", "Tax forms", "Weather alerts", "Grocery lists"], 0],
  ["A brothel is a place for", ["Paid sex", "Bread baking", "Bird watching", "Boat repair"], 0],
  ["Larry Flynt founded which magazine?", ["Hustler", "Playboy", "Vogue", "Time"], 0],
  ["The adult film industry in California is centered in the", ["San Fernando Valley", "Silicon Valley", "Napa Valley", "Death Valley"], 0],
  ["A fleshlight is a type of", ["Male sex toy", "Flashlight", "Kitchen knife", "Camera lens"], 0],
  ["Lube is primarily used to reduce", ["Friction", "Volume", "Temperature", "Gravity"], 0],
  ["A ball gag is used in", ["BDSM play", "Baseball", "Dentistry", "Swimming"], 0],
  ["Nipple clamps are used for", ["Sensation play", "Clothes drying", "Paper holding", "Hair styling"], 0],
  ["Circumcision removes the", ["Foreskin", "Tonsils", "Appendix", "Gallbladder"], 0],
  ["The labia are part of the", ["Vulva", "Elbow", "Knee", "Scalp"], 0],
  ["Testicles produce", ["Sperm", "Insulin", "Bile", "Tears"], 0],
  ["An IUD is inserted into the", ["Uterus", "Stomach", "Lung", "Bladder"], 0],
  ["PrEP helps prevent transmission of", ["HIV", "Flu", "Measles", "Lyme disease"], 0],
  ["A vasectomy blocks", ["Sperm delivery", "Blood flow", "Oxygen intake", "Digestion"], 0],
  ["Herpes is a", ["Sexually transmitted infection", "Vitamin deficiency", "Bone disease", "Eye color"], 0],
  ["HPV can increase risk of", ["Cervical cancer", "Hair loss", "Tooth decay", "Sunburn"], 0],
  ["A strap-on dildo is worn with a", ["Harness", "Helmet", "Backpack", "Belt buckle only"], 0],
  ["Polyamory means having multiple", ["Romantic partners", "Jobs", "Passports", "Cars"], 0],
  ["Swingers often engage in", ["Partner swapping", "Tarot reading", "Rock climbing", "Knitting"], 0],
  ["A sugar daddy typically provides gifts for", ["Companionship", "Homework help", "Car repair", "Gardening"], 0],
  ["A cam girl performs on", ["Webcam", "Ham radio", "Shortwave", "CB radio"], 0],
  ["Fifty Shades of Grey popularized", ["BDSM romance", "Cooking memoirs", "Space opera", "Gardening tips"], 0],
  ["The Joy of Sex is a famous", ["Sex manual", "Cookbook", "Travel guide", "Math textbook"], 0],
  ["Morning wood refers to", ["Nocturnal erection", "Lumber delivery", "Breakfast cereal", "Tree planting"], 0],
  ["A wet dream is an orgasm during", ["Sleep", "Exercise", "Cooking", "Driving"], 0],
  ["An aphrodisiac is believed to increase", ["Libido", "Height", "Shoe size", "Wi-Fi speed"], 0],
  ["Blue balls refers to", ["Testicular aching from arousal", "A sports team", "A candy", "A planet"], 0],
  ["A rimjob involves oral contact with the", ["Anus", "Elbow", "Knee", "Ear"], 0],
  ["Pasties in burlesque cover the", ["Nipples", "Toes", "Fingers", "Ears"], 0],
  ["A stripper pole is used for", ["Pole dancing", "Flag raising", "Clothes drying", "Fishing"], 0],
  ["Skinny dipping means swimming", ["Naked", "In jeans", "In soup", "In mud"], 0],
  ["A walk of shame is leaving after", ["A hookup", "A marathon", "A job interview", "A dentist visit"], 0],
  ["Friends with benefits combine friendship and", ["Casual sex", "Tax advice", "Lawn care", "Tutoring"], 0],
  ["A one night stand is sex without", ["Follow-up relationship", "Consent", "Clothing ever", "Gravity"], 0],
  ["Dirty talk is", ["Erotic speech", "Cleaning instructions", "Weather report", "Sports commentary"], 0],
  ["Lingerie is", ["Sexy underwear", "Winter coat", "Rain boots", "Hard hat"], 0],
  ["A thong is underwear that exposes the", ["Buttocks", "Elbows", "Shins", "Forehead"], 0],
  ["Rule 34 of the internet says if it exists there is", ["Porn of it", "A wiki of it", "A podcast of it", "A NFT of it"], 0],
  ["The banana hammock is slang for a", ["Men's thong swimsuit", "Fruit basket", "Camping tent", "Bike seat"], 0],
  ["Total Recall features a woman with", ["Three breasts", "Four arms", "Two heads", "Wings"], 0],
  ["A merkin in film is used to cover", ["Genitals", "Eyes", "Hands", "Feet"], 0],
  ["Aftercare in kink means comforting after", ["Intense play", "Grocery shopping", "Commuting", "Laundry"], 0],
  ["Edging means delaying", ["Orgasm", "Haircuts", "Emails", "Sunset"], 0],
  ["A flogger is a", ["Multi-tail whip", "Coffee maker", "Printer", "Drum"], 0],
  ["Handcuffs in bedroom play are for", ["Restraint", "Cooking", "Gardening", "Typing"], 0],
  ["Spanking for pleasure is", ["Impact play", "Tax preparation", "Map reading", "Knitting"], 0],
  ["A cuckold fantasy involves a partner with", ["Someone else", "A pet", "A book", "A salad"], 0],
  ["Revenge porn is sharing intimate images", ["Without consent", "With royalty", "On LinkedIn only", "In braille"], 0],
  ["A thirst trap photo aims to attract", ["Sexual attention", "Mosquitoes", "Birds", "Rain"], 0],
  ["The perineum is between genitals and", ["Anus", "Nose", "Ear", "Wrist"], 0],
  ["A rabbit vibrator targets clitoris and", ["G-spot", "Elbow", "Ankle", "Chin"], 0],
  ["The wand massager became famous as a", ["Clitoral vibrator", "Back scratcher", "Door stop", "Paperweight"], 0],
  ["Bukkake is a porn genre involving multiple", ["Ejaculations", "Plot twists", "Cooking scenes", "Car chases"], 0],
  ["A porn set may employ an intimacy", ["Coordinator", "Accountant", "Lifeguard", "Barista"], 0],
  ["Tantric sex emphasizes prolonged", ["Intimacy", "Silence only", "Running", "Fasting"], 0],
  ["A dental dam is thin", ["Latex or polyurethane sheet", "Metal plate", "Wood board", "Glass pane"], 0],
  ["The morning-after pill prevents", ["Pregnancy after sex", "Hangovers", "Jet lag", "Sunburn"], 0],
  ["STI stands for sexually transmitted", ["Infection", "Insurance", "Instruction", "Innovation"], 0],
  ["Chlamydia is often called a silent", ["STI", "Film", "Song", "Recipe"], 0],
  ["OnlyFans lets creators sell", ["Paywalled content", "Used cars", "Real estate", "Airline tickets"], 0],
  ["A hookup culture emphasizes", ["Casual sex", "Long engagements", "Silent retreats", "Early bedtimes"], 0],
  ["An affair is sex outside a", ["Committed relationship", "Gym", "Library", "Park"], 0],
  ["A bachelorette party might hire a", ["Stripper", "Accountant", "Plumber", "Librarian"], 0],
  ["A bachelor party might visit a", ["Strip club", "Library", "Museum", "Church"], 0],
  ["Grinding on the dance floor is", ["Suggestive dancing", "Woodworking", "Cooking rice", "Knitting"], 0],
  ["A horny DM is a", ["Sexual direct message", "Dental message", "Weather alert", "Recipe share"], 0],
  ["OnlyFans was boosted by creators during", ["Pandemic lockdowns", "The moon landing", "The gold rush", "The ice age"], 0],
  ["A sugar baby arrangement trades companionship for", ["Gifts or money", "Homework", "Pet sitting", "Lawn mowing"], 0],
  ["A cam site tip menu lists", ["Custom shows", "Grocery prices", "Bus schedules", "Tax brackets"], 0],
  ["A prostate massage can be done through the", ["Anus", "Ear", "Nose", "Mouth"], 0],
  ["A cock ring should not be worn too long to avoid", ["Tissue damage", "Better Wi-Fi", "Hair growth", "Tanning"], 0],
  ["Lube is especially important for", ["Anal sex", "Reading", "Sleeping", "Walking"], 0],
  ["A butt plug has a flared base to prevent", ["Getting lost inside", "Melting", "Floating away", "Exploding"], 0],
  ["The clitoris has many", ["Nerve endings", "Teeth", "Gills", "Wheels"], 0],
  ["Foreskin protects the sensitive", ["Glans", "Heel", "Palm", "Knee"], 0],
  ["Premature ejaculation means climaxing", ["Too quickly", "Never", "Only on Tuesdays", "Underwater only"], 0],
  ["Erectile dysfunction is difficulty maintaining", ["Erection", "Eye contact", "Balance", "Silence"], 0],
  ["A money shot in porn refers to", ["Ejaculation on camera", "Winning lottery", "Bank robbery", "Sports highlight"], 0],
  ["Blue movie is old slang for", ["Pornographic film", "Sad film", "Ocean documentary", "Sky video"], 0],
  ["Streaking is running", ["Naked in public", "Very slowly", "In mud", "Backwards only"], 0],
  ["A foot fetish is sexual interest in", ["Feet", "Clouds", "Stamps", "Spoons"], 0],
  ["Bondage restricts a partner's", ["Movement", "Appetite", "Accent", "Birthday"], 0],
  ["A blindfold heightens", ["Other senses", "Gravity", "Volume", "Age"], 0],
  ["Roleplay might involve", ["Fantasy characters", "Tax forms", "Bus tickets", "Recipes"], 0],
  ["An orgasm is a peak of", ["Sexual pleasure", "Hunger", "Boredom", "Sleepiness"], 0],
  ["A hookup is a", ["Casual sexual encounter", "Electrical connection", "Fishing trip", "Book club"], 0],
  ["Sexting nudes without consent can be", ["Illegal revenge porn", "Always encouraged", "A tax deduction", "Required"], 0],
  ["A workplace hookup risks", ["HR meetings", "Free pizza", "Extra vacation", "Promotion"], 0],
  ["The spare toothbrush test reveals", ["Overnight guests", "Dental hygiene only", "Allergies", "Favorite color"], 0],
  ["A mysterious bruise after a hookup needs", ["A cover story", "A passport", "A library card", "A trophy"], 0],
].map(([question, choices, correct]) => ({ question, choices, correct }));

const draw = [
  "stripper pole", "three-breasted woman", "banana hammock", "ball gag", "cock ring", "nipple clamps",
  "butt plug", "dildo", "vibrator", "condom", "lingerie", "thong", "lap dance", "pole dance",
  "striptease", "walk of shame", "one night stand", "skinny dipping", "dirty dancing", "merkin",
  "pasties", "glory hole", "fleshlight", "strap-on", "handcuffs", "blindfold", "whip", "flogger",
  "ball gag", "safeword", "dominatrix", "submissive", "bondage rope", "spanking", "love bite",
  "hickey", "morning wood", "wet dream", "blue balls", "orgasm face", "dirty talk", "sexting",
  "thirst trap", "onlyfans logo", "playboy bunny", "red light district", "brothel sign", "escort card",
  "porn director", "fluffer", "money shot", "adult film set", "webcam model", "cam girl",
  "sugar daddy", "sugar baby", "hookup app", "affair text", "secret lover", "cheating spouse",
  "bachelor party", "bachelorette party", "strip club", "pole fitness", "burlesque dancer",
  "lap dancer", "g-string", "crotchless panties", "fishnet stockings", "high heels bedroom",
  "massage oil", "whipped cream bikini", "chocolate body paint", "feather tickler", "ice cube tease",
  "blindfolded partner", "tied to bed", "safe word", "aftercare cuddle", "post-coital pizza",
  "walk of shame heels", "yesterday's makeup", "lost underwear", "stranger's hoodie", "hotel key card",
  "do not disturb sign", "room service champagne", "jacuzzi bubbles", "shower together", "steamy mirror",
  "condom wrapper", "birth control pills", "pregnancy test", "morning after pill", "sti clinic",
  "dental dam", "lube bottle", "anal beads", "rabbit vibrator", "wand massager", "cock sleeve",
  "penis pump", "kegel balls", "prostate massager", "nipple pasties", "chest harness", "leather collar",
  "leash and collar", "spreader bar", "riding crop", "paddle spanking", "wax play", "sensory deprivation",
  "orgy pile", "threesome", "swingers party", "open relationship", "polyamory chart", "cuckold",
  "hotwife", "pegging", "rimjob", "69 position", "missionary", "doggy style", "cowgirl", "reverse cowgirl",
  "spooning sex", "standing sex", "shower sex", "car sex", "airplane bathroom", "mile high club",
  "office affair", "boss employee fling", "teacher student fantasy", "nurse patient roleplay",
  "firefighter calendar", "police handcuffs", "maid outfit", "schoolgirl skirt", "naughty nurse",
  "vampire bite", "werewolf lust", "tentacle hentai", "anime blush", "rule 34", "hentai pillow",
  "blowjob gesture", "deep throat", "cunnilingus", "fingering", "handjob", "mutual masturbation",
  "phone sex", "video call nude", "dick pic", "nude selfie", "bathroom mirror nude", "bedroom mirror",
  "onlyfans selfie", "premium snapchat", "paywall nudes", "tip menu", "custom video request",
  "porn audition", "casting couch", "adult bookstore", "peep show booth", "sex shop", "dildo wall",
  "vibrator aisle", "lube samples", "condom bowl", "penis shaped pasta", "boob cake", "penis cake",
  "stripper cake", "edible underwear", "whipped cream body", "chocolate fountain body", "body shot",
  "body painting nude", "fig leaf", "censored bar", "pixelated nude", "blurred genitals",
  "three breasts", "extra nipple", "camel toe", "bulge outline", "wardrobe malfunction", "nip slip",
  "upskirt paparazzi", "wardrobe oops", "sex tape leak", "revenge porn headline", "affair scandal",
  "tabloid kiss", "cheating caught", "hidden camera", "voyeur window", "exhibitionist flash",
  "streaker field", "nude beach", "nudist colony", "hot tub nude", "sauna towel drop", "locker room",
  "gym shower", "steam room", "massage happy ending", "happy ending joke", "full body massage",
  "tantric massage", "prostate exam joke", "pap smear", "viagra pill", "cialis commercial",
  "erectile dysfunction", "premature ejaculation", "blue pill", "rhino pill", "gas station boner pill",
  "aphrodisiac oyster", "chocolate strawberries", "whipped cream lover", "champagne shower",
  "wedding garter", "garter toss", "wedding night", "honeymoon suite", "heart shaped bed",
  "mirror ceiling", "love hotel", "hourly motel", "no tell motel", "neon motel sign",
];

const bracket = [
  "worst hookup excuses", "spiciest sexting fails", "affair close calls", "strip club disasters",
  "one night stand regrets", "horny group chat moments", "onlyfans career mistakes", "dirty talk disasters",
  "worst thirst traps", "walk of shame outfits", "bachelor party sins", "bachelorette party chaos",
  "workplace hookup scandals", "friends with benefits breakups", "kink discovery stories",
  "safeword mishaps", "sex toy shopping fails", "porn search history reveals", "revenge porn nightmares",
  "sugar daddy red flags", "cam girl technical disasters", "polyamory drama", "swinger party awkwardness",
  "cuckold confession energy", "pegging plot twists", "rimjob regret stories", "morning after mysteries",
  "mysterious bedroom bruises", "hotel key card evidence", "spare toothbrush scandals",
  "affair text autocorrects", "hr meeting after sexting", "boss dm disasters", "cousin plus one hookups",
  "wedding guest affairs", "brunch confession roasts", "screenshot war casualties",
  "deleted chat recoveries", "cloud backup surprises", "smart speaker sex leaks",
  "fridge screen sexting", "car bluetooth confession", "uber rating after hookup",
  "dating app bio horrors", "profile pic lies", "catfish sex reveal", "std scare stories",
  "condom failure panics", "pregnancy test plot twists", "morning after pill runs",
  "brothel tourism tales", "amsterdam window stories", "red light district mishaps",
  "stripper name generators", "lap dance boundary tests", "pole class injuries",
  "burlesque pastie malfunctions", "merkin wardrobe malfunctions", "three-breasted cosplay fails",
  "fetish gear amazon deliveries", "bdsm hotel checkout", "handcuff key panic",
  "blindfold wrong person", "roleplay accent fails", "safeword ignored stories",
  "edging marathon regrets", "blue balls diplomacy", "wet dream confessions",
  "morning wood roommates", "shared bathroom hookups", "thin wall sex neighbors",
  "airbnb sex stain disputes", "sex stain mattress", "love hotel embarrassment",
  "mile high club attempts", "car sex towed", "beach sex police", "public sex fines",
  "nude beach erections", "streaker arrest stories", "skinny dip caught",
  "hot tub orgy rumors", "sauna towel slips", "locker room boners",
  "massage parlor jokes", "happy ending confusion", "tantric workshop awkward",
  "prostate surprise reactions", "g-spot treasure hunts", "clitoris map debates",
  "cock ring stuck stories", "butt plug airport security", "vibrator luggage buzz",
  "dildo wrong bag", "lube stain pants", "condom wallet years",
  "fishnet tear disasters", "lingerie surprise reveals", "crotchless panty fails",
  "whipped cream bikini melts", "chocolate body paint ants", "feather tickler sneezes",
  "wax play burns", "spanking hand cramps", "paddle mark explanations",
  "collar leash public walk", "dominatrix tax writeoffs", "submissive safe word tests",
  "orgy invitation confusion", "threesome third wheel", "unicorn hunter cringe",
  "open relationship rules", "poly chart jealousy", "hotwife anniversary gifts",
  "cuckold podcast pitches", "pegging negotiation talks", "strap-on sizing debates",
  "rimjob breath mints", "69 cramp necks", "missionary boring votes",
  "doggy style carpet burns", "cowgirl knee bruises", "reverse cowgirl disasters",
  "shower sex concussions", "standing sex pulled muscles", "office desk collapses",
  "affair alibi calendars", "secret phone folders", "hidden onlyfans drafts",
  "premium snapchat leaks", "custom video requests", "tip menu regrets",
  "porn audition nerves", "casting couch memes", "adult bookstore exits",
  "peep show coin jams", "sex shop loyalty cards", "dildo wall selfies",
  "penis cake bachelorette", "boob cake accidents", "stripper cake jumps",
  "edible underwear tastes", "body shot salt lines", "nipple shot burns",
  "tabloid kiss photos", "sex tape blackmail", "revenge porn lawsuits",
  "affair podcast episodes", "hr training sext examples", "company slack thirst",
  "family tablet discoveries", "church retreat sexting", "wedding speech dirty quotes",
];

const timeline = [
  { event: "Kinsey publishes Sexual Behavior in the Human Male", year: 1948 },
  { event: "Playboy magazine launches", year: 1953 },
  { event: "The pill is approved for birth control in the US", year: 1960 },
  { event: "Hugh Hefner opens the first Playboy Club", year: 1960 },
  { event: "Lady Chatterley's Lover obscenity trial in the UK", year: 1960 },
  { event: "The Joy of Sex manual is published", year: 1972 },
  { event: "Deep Throat adult film becomes a phenomenon", year: 1972 },
  { event: "Hustler magazine founded by Larry Flynt", year: 1974 },
  { event: "First test-tube baby Louise Brown is born", year: 1978 },
  { event: "HIV/AIDS identified among gay men in the US", year: 1981 },
  { event: "Madonna's Like a Virgin album release", year: 1984 },
  { event: "Surgeon General C. Everett Koop mails AIDS pamphlets", year: 1988 },
  { event: "Total Recall features a three-breasted woman", year: 1990 },
  { event: "Magic Johnson announces HIV-positive status", year: 1991 },
  { event: "The World Wide Web accelerates online porn access", year: 1993 },
  { event: "Friends episode jokes about porn on Monica's TV", year: 1994 },
  { event: "Playboy website launches", year: 1994 },
  { event: "Bill Clinton Lewinsky scandal becomes public", year: 1998 },
  { event: "Sex and the City premieres on HBO", year: 1998 },
  { event: "Viagra approved by the FDA", year: 1998 },
  { event: "Napster era boosts media sharing including adult content", year: 1999 },
  { event: "Big Brother reality show normalizes 24/7 voyeur TV", year: 2000 },
  { event: "Fifty Shades of Grey novel is published", year: 2011 },
  { event: "Fifty Shades of Grey film adaptation releases", year: 2015 },
  { event: "OnlyFans launches", year: 2016 },
  { event: "OnlyFans briefly announces then reverses porn ban", year: 2021 },
  { event: "Pornhub removes unverified uploads after backlash", year: 2020 },
  { event: "Supreme Court legalizes same-sex marriage in the US", year: 2015 },
  { event: "Grindr dating app launches", year: 2009 },
  { event: "Tinder launches and popularizes swipe hookup culture", year: 2012 },
  { event: "Ashley Madison hack exposes affair seekers", year: 2015 },
  { event: "Stormy Daniels hush-money scandal breaks publicly", year: 2018 },
  { event: "MeToo movement goes viral", year: 2017 },
  { event: "Bill Cosby conviction overturned later but trial shook industry", year: 2021 },
  { event: "Harvey Weinstein convicted of sex crimes", year: 2020 },
  { event: "Epstein arrest and death dominate headlines", year: 2019 },
  { event: "Cardi B WAP release sparks cultural debate", year: 2020 },
  { event: "Amsterdam tightens red light district tourism rules", year: 2020 },
  { event: "Germany legalizes prostitution regulation reforms debated", year: 2002 },
  { event: "Nevada brothels operate legally in rural counties", year: 1971 },
  { event: "Roe v. Wade decided in the United States", year: 1973 },
  { event: "Roe v. Wade overturned by Dobbs decision", year: 2022 },
  { event: "Plan B emergency contraception approved OTC in US", year: 2006 },
  { event: "HPV vaccine Gardasil approved", year: 2006 },
  { event: "PrEP approved for HIV prevention", year: 2012 },
  { event: "Monkeypox outbreak linked to sexual networks in 2022 news", year: 2022 },
  { event: "Pornhub parent MindGeek CEO resigns amid scrutiny", year: 2022 },
  { event: "Belle Delphine sells bathwater as stunt", year: 2019 },
  { event: "Cardi B stripper past discussed in interviews", year: 2017 },
  { event: "Miley Cyrus VMA twerking performance", year: 2013 },
  { event: "Janet Jackson Super Bowl wardrobe malfunction", year: 2004 },
  { event: "Prince sings about sex on Purple Rain tour", year: 1984 },
  { event: "Madonna publishes Sex coffee table book", year: 1992 },
  { event: "Caligula controversial adult film release", year: 1979 },
  { event: "Last Tango in Paris butter scene controversy", year: 1972 },
  { event: "Basic Instinct interrogation scene shocks audiences", year: 1992 },
  { event: "Showgirls film becomes cult erotic drama", year: 1995 },
  { event: "Borat thong scene becomes meme", year: 2006 },
  { event: "Magic Mike popularizes male stripper films", year: 2012 },
  { event: "Deadpool jokes about sex and cancer", year: 2016 },
  { event: "Euphoria HBO depicts teen sexuality controversially", year: 2019 },
  { event: "Bridgerton steamy scenes boost Netflix", year: 2020 },
  { event: "Porn literacy courses enter college curricula debates", year: 2021 },
  { event: "Revenge porn laws expand in many US states", year: 2013 },
  { event: "Deepfake porn concerns rise with AI", year: 2017 },
  { event: "AI girlfriend apps trend on app stores", year: 2023 },
  { event: "OnlyFans creators report tax audit confusion", year: 2022 },
  { event: "Stripper labor union efforts make news", year: 2022 },
  { event: "Porn actor unionization debates continue", year: 2020 },
  { event: "Cam site traffic surges during pandemic lockdowns", year: 2020 },
  { event: "Zoom sex scandal memes spread during WFH era", year: 2020 },
  { event: "Tiger King exotic drama includes poly marriage", year: 2020 },
  { event: "Love Is Blind reality show premieres", year: 2020 },
  { event: "Too Hot to Handle no-sex reality show launches", year: 2020 },
  { event: "Sex Education Netflix series premieres", year: 2019 },
  { event: "Big Mouth animated puberty comedy launches", year: 2017 },
  { event: "BoJack Horseman jokes about adult films", year: 2014 },
  { event: "South Park parodies porn addiction", year: 2009 },
  { event: "Family Guy cutaway gags about sex shops", year: 1999 },
  { event: "American Pie pie scene defines teen sex comedy", year: 1999 },
  { event: "American Pie sequel franchise expands", year: 2001 },
  { event: "Superbad fake ID plot for party hookups", year: 2007 },
  { event: "The 40-Year-Old Virgin comedy release", year: 2005 },
  { event: "Knocked Up unplanned pregnancy comedy", year: 2007 },
  { event: "Bridesmaids food poisoning wedding scene", year: 2011 },
  { event: "Girls HBO explores awkward sex scenes", year: 2012 },
  { event: "Normal People intimate scenes praised", year: 2020 },
  { event: "365 Days erotic Netflix film trends", year: 2020 },
  { event: "Fifty Shades Darker sequel releases", year: 2017 },
  { event: "Fifty Shades Freed finale releases", year: 2018 },
  { event: "Pornhub releases its first transparency report under scrutiny", year: 2020 },
  { event: "California passes condom mandate for adult film sets", year: 2016 },
  { event: "Grindr fined for sharing users HIV status with vendors", year: 2021 },
];

const impostor = [
  {
    id: "bedroom-basics",
    label: "Bedroom basics",
    rating: "mature",
    items: [
      "Missionary", "Doggy style", "Cowgirl", "Reverse cowgirl", "Spooning", "Standing sex",
      "Shower sex", "Car sex", "69 position", "Oral sex", "Anal sex", "Foreplay",
      "Dirty talk", "Sexting", "Makeout session", "Lingerie night", "Strip tease", "Massage oil",
      "Safe word", "Aftercare", "Quickie", "Marathon session", "Morning sex", "Lazy Sunday sex",
      "Face sitting", "Prone bone", "Lotus position", "Hand job", "Blow job", "Phone sex",
      "Mutual masturbation", "Tantric sex", "Watching porn together",
    ],
  },
  {
    id: "body-parts",
    label: "Body parts",
    rating: "mature",
    items: [
      "Clitoris", "Penis", "Vagina", "Nipples", "Breasts", "Buttocks", "Anus", "Prostate",
      "Labia", "Scrotum", "Testicles", "Foreskin", "G-spot", "Perineum", "Inner thigh",
      "Neck kiss spot", "Ear lobe", "Lower back", "Hip bone", "Pubic hair", "Belly button",
      "Collarbone", "Wrist pulse", "Lip bite", "Tongue",
    ],
  },
  {
    id: "kinks-fetishes",
    label: "Kinks & fetishes",
    rating: "mature",
    items: [
      "BDSM", "Bondage", "Spanking", "Handcuffs", "Blindfold", "Ball gag", "Nipple clamps",
      "Cock ring", "Butt plug", "Strap-on", "Pegging", "Foot fetish", "Voyeurism", "Exhibitionism",
      "Roleplay", "Dominatrix", "Submissive", "Safeword", "Wax play", "Sensory play",
      "Impact play", "Edging", "Orgasm denial", "Cuckold fantasy", "Threesome fantasy",
    ],
  },
  {
    id: "adult-industry",
    label: "Adult industry",
    rating: "mature",
    items: [
      "Strip club", "Lap dance", "Pole dance", "Burlesque", "OnlyFans", "Cam girl", "Porn set",
      "Adult bookstore", "Peep show", "Red light district", "Brothel", "Escort service",
      "Sugar daddy", "Sugar baby", "Thirst trap", "Premium Snapchat", "Custom video", "Tip menu",
      "Fluffer", "Director", "Money shot", "Hardcore scene", "Softcore scene", "Intimacy coordinator",
    ],
  },
  {
    id: "hookup-mishaps",
    label: "Hookup mishaps",
    rating: "mature",
    items: [
      "Walk of shame", "One night stand", "Wrong name moan", "Lost underwear", "Stranger hoodie",
      "Hotel key card", "Do not disturb", "Spare toothbrush", "Mysterious bruise", "4am Venmo",
      "Screenshot leak", "Group chat recap", "Affair text", "Wrong person DM", "Autocorrect disaster",
      "HR meeting", "Caught by roommate", "Thin walls", "Uber rating fight", "Breakfast avoidance",
      "Fake number", "Ghosting", "Leftover pizza box", "Shared bathroom panic",
      "Wrong Uber pickup", "Hotel minibar regret", "Sex stain dispute", "Walk of shame heels",
      "Booty call", "Dick pic", "Condom broke", "Plan B run", "Pregnancy scare", "Whiskey dick",
      "Blue balls", "Performance anxiety", "Caught by parents", "LinkedIn stalk",
    ],
  },
];

const reverseFact = [
  { fact: "Hugh Hefner", truth: "Who founded Playboy magazine?" },
  { fact: "Larry Flynt", truth: "Who founded Hustler magazine?" },
  { fact: "Gräfenberg", truth: "The G-spot is named after Ernst who?" },
  { fact: "India", truth: "Where did the Kama Sutra originate?" },
  { fact: "hysteria", truth: "Victorian vibrators were sold to treat female what?" },
  { fact: "baculum", truth: "What is the penis bone called in many mammals?" },
  { fact: "Grindr", truth: "Which dating app launched in 2009 for gay men?" },
  { fact: "Tinder", truth: "Which app popularized swipe hookup culture in 2012?" },
  { fact: "Viagra", truth: "Which blue pill was FDA-approved in 1998?" },
  { fact: "OnlyFans", truth: "Which creator platform launched in 2016?" },
  { fact: "Fifty Shades", truth: "Which novel popularized BDSM romance in 2011?" },
  { fact: "Deep Throat", truth: "Which 1972 adult film became a cultural phenomenon?" },
  { fact: "Kinsey", truth: "Who published landmark sexual behavior studies in 1948?" },
  { fact: "Amsterdam", truth: "Which city is famous for the De Wallen red light district?" },
  { fact: "prostitution", truth: "What is often called the world's oldest profession?" },
  { fact: "clitoris", truth: "Which organ has roughly twice the nerve endings of the penis?" },
  { fact: "prostate", truth: "What gland is sometimes called the male G-spot?" },
  { fact: "pegging", truth: "What is it called when a woman anally penetrates a man with a strap-on?" },
  { fact: "merkin", truth: "What is a fake pubic wig called on film sets?" },
  { fact: "fellatio", truth: "What is oral sex on a penis called?" },
  { fact: "cunnilingus", truth: "What is oral sex on the vulva called?" },
  { fact: "hentai", truth: "What is Japanese animated pornography called?" },
  { fact: "burlesque", truth: "What performance art often features striptease?" },
  { fact: "safeword", truth: "What word in BDSM means stop immediately?" },
  { fact: "fluffer", truth: "Who on an adult set helps performers stay aroused?" },
  { fact: "PrEP", truth: "What HIV prevention regimen was approved in 2012?" },
  { fact: "HPV", truth: "Which STI can increase cervical cancer risk?" },
  { fact: "chlamydia", truth: "Which STI is often called silent?" },
  { fact: "vasectomy", truth: "Which procedure blocks sperm delivery?" },
  { fact: "IUD", truth: "Which birth control device is inserted in the uterus?" },
  { fact: "dental dam", truth: "What thin barrier is used during oral sex?" },
  { fact: "strap-on", truth: "What harness-held toy is used for pegging?" },
  { fact: "butt plug", truth: "What toy is inserted in the anus with a flared base?" },
  { fact: "cock ring", truth: "What device restricts blood flow to maintain erection?" },
  { fact: "ball gag", truth: "What BDSM item fills the mouth?" },
  { fact: "nipple clamps", truth: "What BDSM toys pinch the nipples?" },
  { fact: "voyeurism", truth: "What kink involves arousal from watching others?" },
  { fact: "exhibitionism", truth: "What kink involves arousal from being watched?" },
  { fact: "polyamory", truth: "What is having multiple romantic partners called?" },
  { fact: "swingers", truth: "What are couples who swap partners called?" },
  { fact: "sugar daddy", truth: "Who provides gifts for companionship in an arrangement?" },
  { fact: "cam girl", truth: "Who performs sexually on a webcam for tips?" },
  { fact: "thirst trap", truth: "What is a photo meant to attract sexual attention?" },
  { fact: "sexting", truth: "What is sending sexual messages called?" },
  { fact: "hookup", truth: "What is a casual sexual encounter called?" },
  { fact: "affair", truth: "What is sex outside a committed relationship called?" },
  { fact: "orgy", truth: "What is group sex often called?" },
  { fact: "threesome", truth: "What do you call sex with three people?" },
  { fact: "missionary", truth: "Which position is named after colonial missionaries?" },
  { fact: "doggy style", truth: "Which position is rear-entry sex?" },
  { fact: "cowgirl", truth: "Which position has the receptive partner on top?" },
  { fact: "lap dance", truth: "What dance is performed on a seated customer?" },
  { fact: "strip club", truth: "Where do performers do striptease for money?" },
  { fact: "brothel", truth: "Where is paid sex often arranged?" },
  { fact: "red light", truth: "What color of window is associated with legal sex districts?" },
  { fact: "pornography", truth: "What media is intended to cause sexual arousal?" },
  { fact: "OnlyFans", truth: "Which site lets creators sell paywalled adult content?" },
  { fact: "Rule 34", truth: "Which internet rule says if it exists there is porn of it?" },
  { fact: "Total Recall", truth: "Which film features a three-breasted woman?" },
  { fact: "banana hammock", truth: "What is slang for a men's thong swimsuit?" },
  { fact: "morning wood", truth: "What is a common nocturnal erection called?" },
  { fact: "wet dream", truth: "What is an orgasm during sleep called?" },
  { fact: "blue balls", truth: "What slang describes testicular aching from arousal?" },
  { fact: "walk of shame", truth: "What is leaving after a hookup called?" },
  { fact: "skinny dipping", truth: "What is swimming naked called?" },
  { fact: "dirty talk", truth: "What is erotic speech during sex called?" },
  { fact: "lingerie", truth: "What is sexy underwear called?" },
  { fact: "foreplay", truth: "What sexual activity builds arousal before intercourse?" },
  { fact: "orgasm", truth: "What is the peak of sexual pleasure called?" },
  { fact: "libido", truth: "What is sexual drive called?" },
  { fact: "aphrodisiac", truth: "What is something believed to increase libido?" },
  { fact: "circumcision", truth: "What procedure removes the foreskin?" },
  { fact: "labia", truth: "What folds are part of the vulva?" },
  { fact: "scrotum", truth: "What sac holds the testicles?" },
  { fact: "testicles", truth: "What organs produce sperm?" },
  { fact: "foreskin", truth: "What skin covers the penis glans?" },
  { fact: "anus", truth: "What opening is involved in anal sex?" },
  { fact: "lube", truth: "What reduces friction during sex?" },
  { fact: "condom", truth: "What barrier method prevents pregnancy and STIs?" },
  { fact: "vibrator", truth: "What device provides sexual stimulation?" },
  { fact: "dildo", truth: "What is a penis-shaped sex toy called?" },
  { fact: "fleshlight", truth: "What brand makes a popular penis sleeve toy?" },
  { fact: "dominatrix", truth: "What is a woman in a dominant BDSM role called?" },
  { fact: "submissive", truth: "What partner takes a yielding BDSM role?" },
  { fact: "aftercare", truth: "What comforting practice follows intense kink play?" },
  { fact: "edging", truth: "What practice delays orgasm on purpose?" },
  { fact: "cuckold", truth: "What fantasy involves a partner with someone else?" },
  { fact: "revenge porn", truth: "What is sharing intimate images without consent?" },
  { fact: "Ashley Madison", truth: "Which affair site was hacked in 2015?" },
  { fact: "Stormy Daniels", truth: "Which adult film actor was in a 2018 hush-money scandal?" },
  { fact: "Magic Mike", truth: "Which 2012 film popularized male strippers?" },
  { fact: "Showgirls", truth: "Which 1995 erotic drama became a cult film?" },
  { fact: "Sex Education", truth: "Which 2019 Netflix show tackles teen sexuality?" },
  { fact: "Euphoria", truth: "Which HBO show depicts teen sex controversially?" },
  { fact: "Bridgerton", truth: "Which Netflix period drama became famous for steamy scenes?" },
  { fact: "Cardi B", truth: "Who released the song WAP in 2020?" },
  { fact: "Janet Jackson", truth: "Who had a Super Bowl wardrobe malfunction in 2004?" },
  { fact: "Madonna", truth: "Who published the Sex coffee table book in 1992?" },
  { fact: "Bill Clinton", truth: "Which US president was in the Lewinsky scandal?" },
  { fact: "Lewinsky", truth: "Who was at the center of the 1998 White House scandal?" },
  { fact: "Roe", truth: "Which 1973 case legalized abortion in the US?" },
  { fact: "Dobbs", truth: "Which 2022 decision overturned Roe v. Wade?" },
  { fact: "MindGeek", truth: "Which company owns Pornhub?" },
  { fact: "Belle Delphine", truth: "Who sold bathwater as a stunt in 2019?" },
  { fact: "deepfake", truth: "What AI-generated fake media raised porn concerns in 2017?" },
  { fact: "mile high", truth: "What club means sex on an airplane?" },
  { fact: "happy ending", truth: "What massage joke implies sexual finish?" },
  { fact: "money shot", truth: "What porn term means ejaculation on camera?" },
  { fact: "blue movie", truth: "What is old slang for a pornographic film?" },
  { fact: "streaking", truth: "What is running naked in public called?" },
  { fact: "pasties", truth: "What cover nipples in burlesque shows?" },
  { fact: "g-string", truth: "What minimal underwear exposes the buttocks?" },
  { fact: "fishnets", truth: "What patterned stockings are stripper clichés?" },
  { fact: "whipped cream", truth: "What dessert topping is used in body shots?" },
  { fact: "body shot", truth: "What drink is taken off someone's body?" },
  { fact: "edible underwear", truth: "What candy garment is a bachelorette gag gift?" },
  { fact: "penis cake", truth: "What shaped dessert appears at bachelorette parties?" },
  { fact: "garter toss", truth: "What wedding tradition involves the groom's toss?" },
  { fact: "honeymoon suite", truth: "What hotel room is booked after a wedding?" },
  { fact: "love hotel", truth: "What hourly lodging is famous in Japan?" },
  { fact: "mile high club", truth: "What do you join after sex on a plane?" },
];

/** Verified historical dates only — not template-generated. */
const timelineVerifiedExtra: Array<{ event: string; year: number }> = [
  { event: "Comstock Act restricts contraceptive information in the US", year: 1873 },
  { event: "First birth control clinic opens in the US (Margaret Sanger)", year: 1916 },
  { event: "Kinsey Institute founded at Indiana University", year: 1947 },
  { event: "First issue of Playboy magazine published", year: 1953 },
  { event: "FDA approves birth control pill Enovid", year: 1960 },
  { event: "Betty Friedan publishes The Feminine Mystique", year: 1963 },
  { event: "Griswold v. Connecticut establishes marital privacy on contraception", year: 1965 },
  { event: "Summer of Love in San Francisco", year: 1967 },
  { event: "Stonewall riots in New York City", year: 1969 },
  { event: "First Gay Pride marches in US cities", year: 1970 },
  { event: "Larry Flynt founds Hustler magazine", year: 1974 },
  { event: "Rocky Horror Picture Show premieres", year: 1975 },
  { event: "Anita Bryant anti-gay Save Our Children campaign", year: 1977 },
  { event: "First national March on Washington for Lesbian and Gay Rights", year: 1979 },
  { event: "First reported AIDS cases in the US", year: 1981 },
  { event: "Surgeon General report on AIDS released", year: 1986 },
  { event: "Ryan White dies of AIDS complications", year: 1990 },
  { event: "Magic Johnson announces he is HIV-positive", year: 1991 },
  { event: "Bill Clinton elected after Gennifer Flowers scandal", year: 1992 },
  { event: "Don't Ask Don't Tell policy enacted in US military", year: 1993 },
  { event: "Jeffrey Dahmer trial raises serial killer media frenzy", year: 1992 },
  { event: "The Jerry Springer Show peaks in tabloid TV ratings", year: 1998 },
  { event: "Monica Lewinsky scandal breaks publicly", year: 1998 },
  { event: "Sex and the City premieres on HBO", year: 1998 },
  { event: "FDA approves Viagra for erectile dysfunction", year: 1998 },
  { event: "Matthew Shepard murdered in Wyoming", year: 1998 },
  { event: "Boston Legalizes same-sex marriage in Massachusetts", year: 2004 },
  { event: "Brokeback Mountain released in theaters", year: 2005 },
  { event: "Twitter launches and later becomes thirst-trap platform", year: 2006 },
  { event: "iPhone launch enables mobile sexting culture", year: 2007 },
  { event: "Craigslist removes adult services section after pressure", year: 2010 },
  { event: "Grindr app launches globally", year: 2009 },
  { event: "Tinder launches swipe-based dating", year: 2012 },
  { event: "Anthony Weiner sexting scandal resurfaces", year: 2011 },
  { event: "Fifty Shades of Grey book tops bestseller lists", year: 2012 },
  { event: "Supreme Court strikes down DOMA section 3", year: 2013 },
  { event: "Celebgate iCloud photo leak scandal", year: 2014 },
  { event: "Ashley Madison user data breach", year: 2015 },
  { event: "Supreme Court legalizes same-sex marriage nationwide in Obergefell", year: 2015 },
  { event: "Bathroom bills debate peaks in North Carolina", year: 2016 },
  { event: "Harvey Weinstein allegations published in New York Times", year: 2017 },
  { event: "MeToo hashtag goes viral after Weinstein reports", year: 2017 },
  { event: "Kevin Spacey allegations lead to House of Cards cancellation", year: 2017 },
  { event: "Aziz Ansari date story sparks consent debate", year: 2018 },
  { event: "Stormy Daniels hush money case enters mainstream news", year: 2018 },
  { event: "Jeffrey Epstein arrested on sex trafficking charges", year: 2019 },
  { event: "OnlyFans surges during COVID lockdowns", year: 2020 },
  { event: "Cardi B releases WAP with Megan Thee Stallion", year: 2020 },
  { event: "Pornhub removes unverified uploads", year: 2020 },
  { event: "OnlyFans announces then reverses adult content ban", year: 2021 },
  { event: "Roe v. Wade overturned by Dobbs v. Jackson", year: 2022 },
  { event: "Johnny Depp v. Amber Heard defamation trial aired", year: 2022 },
  { event: "Britney Spears conservatorship ends after Free Britney movement", year: 2021 },
  { event: "Bill Cosby conviction overturned on procedural grounds", year: 2021 },
  { event: "Larry Nassar USA Gymnastics abuse sentencing hearings", year: 2018 },
  { event: "Larry Flynt dies", year: 2021 },
  { event: "Hugh Hefner dies", year: 2017 },
  { event: "Christine Jorgensen gender affirmation story makes headlines", year: 1952 },
  { event: "First transgender person on cover of Time magazine (Laverne Cox era)", year: 2014 },
  { event: "Paris Hilton sex tape scandal era in tabloid culture", year: 2004 },
  { event: "Pamela Anderson and Tommy Lee tape theft scandal", year: 1995 },
  { event: "Bill Clinton impeachment over Lewinsky affair", year: 1998 },
  { event: "Eliot Spitzer prostitution scandal forces resignation", year: 2008 },
  { event: "Anthony Weiner resigns from Congress over sexting", year: 2011 },
  { event: "David Petraeus resigns CIA over affair", year: 2012 },
  { event: "Dominique Strauss-Kahn hotel maid accusation case", year: 2011 },
  { event: "R. Kelly convicted on sex trafficking charges", year: 2021 },
  { event: "Ghislaine Maxwell convicted for Epstein trafficking conspiracy", year: 2021 },
  { event: "Britney Spears conservatorship hearing goes viral", year: 2021 },
  { event: "OnlyFans creator Bella Thorne payment controversy", year: 2020 },
  { event: "Pornhub deletes millions of unverified videos", year: 2020 },
  { event: "Netflix releases 365 Days erotic film", year: 2020 },
  { event: "Bridgerton steamy scenes trend on Netflix", year: 2020 },
  { event: "Euphoria teen sexuality debates begin on HBO", year: 2019 },
  { event: "Nymphomaniac film by Lars von Trier premieres", year: 2013 },
  { event: "Blue Is the Warmest Color wins Palme d'Or at Cannes", year: 2013 },
  { event: "Fifty Shades Freed film finale releases", year: 2018 },
  { event: "Magic Mike XXL sequel releases", year: 2015 },
  { event: "Deadpool R-rated superhero film embraces sex humor", year: 2016 },
  { event: "Borat Subsequent Moviefilm release with crude humor", year: 2020 },
  { event: "Salt-N-Pepa push condom awareness in pop culture", year: 1991 },
  { event: "Madonna Like a Prayer video controversy", year: 1989 },
  { event: "Prince Sign o the Times tour famous for sexuality", year: 1987 },
  { event: "George Michael arrested in public restroom scandal", year: 1998 },
  { event: "Rob Lowe sex tape scandal", year: 1988 },
  { event: "Rebecca Schaeffer murder sparks anti-stalking laws debate", year: 1989 },
  { event: "Revenge porn laws spread across US states", year: 2013 },
  { event: "Deepfake porn concerns rise with AI tools", year: 2017 },
  { event: "California requires condoms on adult film sets (Measure B era debate)", year: 2012 },
  { event: "Nevada legal brothels operate in rural counties", year: 1971 },
  { event: "Germany passes Prostitution Act regulating sex work", year: 2002 },
  { event: "Sweden introduces Nordic model on purchasing sex", year: 1999 },
  { event: "Amsterdam tightens red light district tourism", year: 2020 },
  { event: "UK age verification for porn sites proposed then dropped", year: 2019 },
  { event: "FOSTA-SESTA US law affects online sex work ads", year: 2018 },
  { event: "Backpage.com seized by federal authorities", year: 2018 },
  { event: "Craigslist personals section removed in US", year: 2018 },
  { event: "Tumblr bans adult content", year: 2018 },
  { event: "Patreon adult content policy debates", year: 2018 },
  { event: "Discord adult content moderation debates intensify", year: 2021 },
  { event: "Reddit bans several sexualized subreddits in policy updates", year: 2015 },
  { event: "Snapchat introduced disappearing messages changing sexting", year: 2011 },
  { event: "Instagram introduces Stories competing with Snapchat", year: 2016 },
  { event: "TikTok thirst trap culture dominates Gen Z social media", year: 2020 },
  { event: "Bumble IPO as women-message-first dating app", year: 2021 },
  { event: "Hinge rebrands as designed to be deleted", year: 2019 },
  { event: "COVID lockdowns increase cam site traffic reports", year: 2020 },
  { event: "Zoom sex scandal memes during remote work era", year: 2020 },
  { event: "Lady Gaga Born This Way anthem boosts LGBTQ visibility", year: 2011 },
  { event: "RuPaul Drag Race premieres and mainstreams drag culture", year: 2009 },
  { event: "Queer Eye reboot premieres on Netflix", year: 2018 },
  { event: "Pose FX series highlights ballroom and trans stories", year: 2018 },
  { event: "Ellen DeGeneres comes out on magazine cover", year: 1997 },
  { event: "Will and Grace premieres with gay lead characters", year: 1998 },
  { event: "Brokeback Mountain Oscar buzz for gay cowboy romance", year: 2005 },
  { event: "Moonlight wins Best Picture after envelope mix-up", year: 2017 },
  { event: "Call Me by Your Name queer romance film release", year: 2017 },
  { event: "Portrait of a Lady on Fire arthouse lesbian romance", year: 2019 },
  { event: "Cuties Netflix film sparks sexualization debate", year: 2020 },
  { event: "Cuties controversy fuels culture war over minors on screen", year: 2020 },
  { event: "Andrew Tate banned on platforms amid misogyny debates", year: 2022 },
  { event: "Incel forum culture enters mainstream news coverage", year: 2014 },
  { event: "Gamergate harassment campaign targets women in gaming", year: 2014 },
  { event: "OnlyFans creator Bella Thorne payment backlash", year: 2020 },
  { event: "Pornhub deletes unverified videos after NY Times report", year: 2020 },
  { event: "MindGeek CEO resigns amid Pornhub scrutiny", year: 2022 },
  { event: "Louis C.K. admits sexual misconduct allegations", year: 2017 },
  { event: "Aziz Ansari date story sparks consent debate", year: 2018 },
  { event: "Brett Kavanaugh hearing includes sexual assault testimony", year: 2018 },
  { event: "Christine Blasey Ford testifies in Kavanaugh hearing", year: 2018 },
  { event: "Bill Cosby sentenced then conviction later overturned", year: 2018 },
  { event: "Larry Nassar sentencing hearing with survivor statements", year: 2018 },
  { event: "USA Gymnastics sexual abuse scandal dominates news", year: 2016 },
  { event: "Catholic Church sexual abuse investigations global headlines", year: 2002 },
  { event: "Jeffrey Epstein found dead in jail awaiting trial", year: 2019 },
  { event: "Prince Andrew settles Virginia Giuffre lawsuit", year: 2022 },
  { event: "Harvey Weinstein sentenced for sexual assault crimes", year: 2020 },
  { event: "Kevin Spacey criminal sexual assault trial in UK", year: 2023 },
  { event: "Johnny Depp v Amber Heard televised defamation trial", year: 2022 },
  { event: "Britney Spears conservatorship terminated after fan campaign", year: 2021 },
  { event: "Free Britney movement protests outside courthouses", year: 2021 },
  { event: "SlutWalk marches protest victim blaming after Toronto case", year: 2011 },
  { event: "Yes Means Yes affirmative consent laws debated in colleges", year: 2014 },
  { event: "California affirmative consent law for campuses signed", year: 2014 },
  { event: "Plan B emergency contraception approved over the counter", year: 2006 },
  { event: "Emergency contraception morning-after pill OTC debate peaks", year: 2006 },
  { event: "HPV vaccine Gardasil recommended for adolescents", year: 2006 },
  { event: "FDA approves female Viagra Addyi for low libido", year: 2015 },
  { event: "Sex therapy shows like Couples Therapy trend on streaming", year: 2021 },
  { event: "Supreme Court hears Obergefell same-sex marriage arguments", year: 2015 },
  { event: "Grindr launches globally for gay dating", year: 2009 },
  { event: "Tinder launches swipe hookup culture era", year: 2012 },
  { event: "OnlyFans launches creator subscription platform", year: 2016 },
  { event: "Pornhub removes unverified videos after backlash", year: 2020 },
  { event: "Deep Throat adult film cultural phenomenon peaks", year: 1972 },
  { event: "Playboy magazine first issue published", year: 1953 },
  { event: "Kinsey Reports on human sexuality published", year: 1948 },
  { event: "FDA approves Viagra for erectile dysfunction", year: 1998 },
  { event: "Magic Johnson announces HIV-positive status", year: 1991 },
];

const reverseFactVerifiedExtra: Array<{ fact: string; truth: string }> = [
  { fact: "Kinsey", truth: "Who published landmark sexual behavior studies in 1948?" },
  { fact: "Enovid", truth: "What was the first FDA-approved birth control pill?" },
  { fact: "Obergefell", truth: "Which Supreme Court case legalized same-sex marriage nationwide?" },
  { fact: "Griswold", truth: "Which case established marital privacy on contraception?" },
  { fact: "Stonewall", truth: "Which 1969 riots launched modern LGBTQ activism?" },
  { fact: "Viagra", truth: "Which pill was FDA-approved for erectile dysfunction in 1998?" },
  { fact: "Grindr", truth: "Which app launched in 2009 for gay dating?" },
  { fact: "Tinder", truth: "Which app popularized swipe dating in 2012?" },
  { fact: "Bumble", truth: "Which dating app requires women to message first?" },
  { fact: "Hinge", truth: "Which dating app markets itself as designed to be deleted?" },
  { fact: "FOSTA-SESTA", truth: "Which US law affected online sex work ads in 2018?" },
  { fact: "Backpage", truth: "Which classifieds site was seized in 2018?" },
  { fact: "Epstein", truth: "Who was arrested on sex trafficking charges in 2019?" },
  { fact: "Maxwell", truth: "Who was convicted in the Epstein trafficking conspiracy?" },
  { fact: "Weinstein", truth: "Which producer's allegations sparked MeToo in 2017?" },
  { fact: "MeToo", truth: "Which movement went viral after Weinstein reports?" },
  { fact: "Lewinsky", truth: "Who was central to the 1998 White House scandal?" },
  { fact: "Spitzer", truth: "Which New York governor resigned over a prostitution scandal?" },
  { fact: "Petraeus", truth: "Which CIA director resigned over an affair in 2012?" },
  { fact: "Weiner", truth: "Which politician resigned over sexting in 2011?" },
  { fact: "Pamela Anderson", truth: "Which Baywatch star was in a 1990s stolen tape scandal?" },
  { fact: "Paris Hilton", truth: "Which socialite's 2004 tape scandal dominated tabloids?" },
  { fact: "Rob Lowe", truth: "Which Brat Pack actor had a 1988 sex tape scandal?" },
  { fact: "George Michael", truth: "Which singer was arrested in a 1998 restroom scandal?" },
  { fact: "Ryan White", truth: "Whose AIDS death in 1990 raised public awareness?" },
  { fact: "Magic Johnson", truth: "Which NBA star announced HIV-positive status in 1991?" },
  { fact: "PrEP", truth: "What regimen helps prevent HIV transmission?" },
  { fact: "DOMA", truth: "Which US law defined marriage federally before 2013?" },
  { fact: "Obergefell v. Hodges", truth: "Which case legalized same-sex marriage in 2015?" },
  { fact: "Roe", truth: "Which 1973 case legalized abortion in the US?" },
  { fact: "Dobbs", truth: "Which 2022 case overturned Roe v. Wade?" },
  { fact: "Sanger", truth: "Who opened the first US birth control clinic in 1916?" },
  { fact: "Comstock Act", truth: "Which 1873 law restricted contraceptive information?" },
  { fact: "Deep Throat", truth: "Which 1972 adult film became a cultural phenomenon?" },
  { fact: "Showgirls", truth: "Which 1995 erotic drama became a cult film?" },
  { fact: "Magic Mike", truth: "Which 2012 film popularized male strippers?" },
  { fact: "Brokeback Mountain", truth: "Which 2005 film depicted a gay cowboy romance?" },
  { fact: "Bridgerton", truth: "Which Netflix period drama became famous for steamy scenes?" },
  { fact: "Euphoria", truth: "Which HBO show depicts teen sexuality controversially?" },
  { fact: "Sex Education", truth: "Which Netflix show tackles teen sexuality?" },
  { fact: "365 Days", truth: "Which erotic Netflix film trended in 2020?" },
  { fact: "WAP", truth: "Which 2020 Cardi B song sparked cultural debate?" },
  { fact: "Belle Delphine", truth: "Who sold bathwater as a stunt in 2019?" },
  { fact: "MindGeek", truth: "Which company owns Pornhub?" },
  { fact: "Craigslist", truth: "Which site removed personals after FOSTA-SESTA?" },
  { fact: "Tumblr", truth: "Which platform banned adult content in 2018?" },
  { fact: "Snapchat", truth: "Which app introduced disappearing messages in 2011?" },
  { fact: "Zoom", truth: "Which remote-work tool spawned sex scandal memes in 2020?" },
  { fact: "Nevada", truth: "Which US state allows legal brothels in rural counties?" },
  { fact: "Amsterdam", truth: "Which city is famous for the De Wallen red light district?" },
  { fact: "Germany", truth: "Which country passed a Prostitution Act in 2002?" },
  { fact: "Sweden", truth: "Which country introduced the Nordic model on buying sex in 1999?" },
  { fact: "FOSTA", truth: "Which US anti-trafficking law affected online adult ads?" },
  { fact: "revenge porn", truth: "What is sharing intimate images without consent?" },
  { fact: "deepfake", truth: "What AI fake media raised porn concerns in 2017?" },
  { fact: "intimacy coordinator", truth: "Who choreographs safe sex scenes on sets?" },
  { fact: "money shot", truth: "What porn term means ejaculation on camera?" },
  { fact: "fluffer", truth: "Who on an adult set helps performers stay aroused?" },
  { fact: "merkin", truth: "What is a fake pubic wig on film sets?" },
  { fact: "pasties", truth: "What covers nipples in burlesque shows?" },
  { fact: "mile high club", truth: "What do you join after sex on a plane?" },
];

function dedupeTimeline(rows: Array<{ event: string; year: number }>) {
  const seen = new Set<string>();
  return rows.filter((row) => {
    const key = `${row.event}|${row.year}`.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function dedupeReverse(rows: Array<{ fact: string; truth: string }>) {
  const seen = new Set<string>();
  return rows.filter((row) => {
    const key = `${row.fact}|${row.truth}`.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function dedupeStrings(items: string[]) {
  const seen = new Set<string>();
  return items.filter((item) => {
    const k = item.toLowerCase();
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
}

/** Verified sex-ed / culture trivia MCQs — not combinator-generated. */
const quizVerifiedExtra: Array<{ question: string; choices: string[]; correct: number }> = [
  ["What does STI stand for?", ["Sexually transmitted infection", "Sexual therapy institute", "Safe touch instruction", "Standard test interval"], 0],
  ["Which organ is primarily for sexual pleasure in many women?", ["Clitoris", "Appendix", "Spleen", "Pancreas"], 0],
  ["A dental dam is used as a barrier during", ["Oral sex", "Dental surgery only", "Weight lifting", "Swimming"], 0],
  ["Which hormone drives libido in all genders?", ["Testosterone", "Insulin", "Adrenaline only", "Melatonin"], 0],
  ["What is the most common STI in many countries?", ["HPV", "Malaria", "Flu", "Lyme disease"], 0],
  ["Which practice delays orgasm on purpose?", ["Edging", "Sprinting", "Fasting", "Stretching"], 0],
  ["A safeword in kink means", ["Stop immediately", "Go harder", "Switch roles", "Take a photo"], 0],
  ["Which term describes paid sexual services?", ["Sex work", "Tax work", "Team work", "Wood work"], 0],
  ["Fetish refers to", ["Sexual fixation on something", "A type of shoe polish", "A chess opening", "A pasta shape"], 0],
  ["Which body part produces sperm?", ["Testicles", "Kidneys", "Lungs", "Liver"], 0],
  ["Which body part produces eggs?", ["Ovaries", "Stomach", "Bladder", "Thyroid"], 0],
  ["What does LGBTQ stand for broadly?", ["Lesbian gay bisexual transgender queer", "Long great big quiet unicorns", "Legal group business trust", "Local gym ballet club"], 0],
  ["Consent must be", ["Freely given and ongoing", "Assumed after one yes", "Optional in marriage only", "Silent always"], 0],
  ["Which fluid can transmit HIV?", ["Blood and sexual fluids", "Tears only", "Sweat only", "Saliva always"], 0],
  ["PrEP helps prevent", ["HIV infection", "Pregnancy only", "Hangover", "Sunburn"], 0],
  ["Plan B is an", ["Emergency contraceptive", "Energy drink", "Allergy pill", "Vitamin"], 0],
  ["Which is a barrier contraceptive?", ["Condom", "Aspirin", "Ibuprofen", "Antacid"], 0],
  ["The vulva includes the", ["External female genitals", "Uterus only", "Ovaries only", "Fallopian tubes only"], 0],
  ["Erection in the penis involves blood filling the", ["Corpora cavernosa", "Stomach", "Lungs", "Eardrum"], 0],
  ["Anal sex without lube increases risk of", ["Tearing and discomfort", "Better Wi-Fi", "Hair growth", "Tanning"], 0],
  ["Which is a common symptom of many STIs?", ["Often none at first", "Always a rash on day one", "Always fever in an hour", "Always blindness"], 0],
  ["OnlyFans is primarily a", ["Creator subscription platform", "Food delivery app", "Ride share app", "Bank"], 0],
  ["Burlesque often includes", ["Striptease performance", "Opera only", "Ballet only", "Magic only"], 0],
  ["A dominatrix is typically", ["A dominant partner in BDSM", "A type of coffee", "A chess piece", "A shoe brand"], 0],
  ["Polyamory means", ["Multiple consensual partners", "One partner only", "No dating ever", "Only online dating"], 0],
  ["Swinger culture often involves", ["Consensual partner swapping", "Only board games", "Only church events", "Only hiking"], 0],
  ["Revenge porn is", ["Sharing intimate images without consent", "A movie genre only", "A card game", "A cooking style"], 0],
  ["Sexting is", ["Sending sexual digital messages", "Texting about sports", "Emailing recipes", "Faxing forms"], 0],
  ["A strip club is where performers do", ["Striptease", "Surgery", "Tax prep", "Tutoring"], 0],
  ["The prostate can be stimulated through the", ["Anus", "Ear", "Nose", "Elbow"], 0],
  ["Circumcision removes the", ["Foreskin", "Tonsils", "Appendix", "Gallbladder"], 0],
  ["The G-spot is associated with the", ["Anterior vaginal wall", "Elbow", "Knee", "Heel"], 0],
  ["A cock ring is worn to help maintain", ["Erection", "Hair style", "Balance", "Appetite"], 0],
  ["A butt plug has a flared base to prevent", ["Getting lost inside", "Melting", "Floating away", "Exploding"], 0],
  ["Hentai is", ["Japanese animated pornography", "A sushi roll", "A martial art", "A board game"], 0],
  ["Rule 34 of the internet claims", ["If it exists there is porn of it", "Cats rule the web", "Email is dead", "Wi-Fi is free"], 0],
  ["A merkin is", ["A pubic wig", "A bird", "A car part", "A cheese"], 0],
  ["Fellatio is oral contact with the", ["Penis", "Elbow", "Knee", "Ear"], 0],
  ["Cunnilingus is oral contact with the", ["Vulva", "Penis", "Ankle", "Wrist"], 0],
  ["Pegging involves", ["Strap-on anal penetration", "Fishing", "Knitting", "Golf"], 0],
].map(([question, choices, correct]) => ({ question, choices, correct }));

const creative = generateCreativePools();
const timelineAll = dedupeTimeline([...timeline, ...timelineVerifiedExtra]);
const reverseAll = dedupeReverse([...reverseFact, ...reverseFactVerifiedExtra]);
const quizAll = [...quiz, ...quizVerifiedExtra];
const drawAll = dedupeStrings([...draw, ...creative.draw]);
const bracketAll = dedupeStrings([...bracket, ...creative.bracket]);
const impostorAll = expandImpostorItems(impostor);

writeFileSync(
  OUT,
  `${JSON.stringify(
    {
      factCheck,
      quiz: quizAll,
      draw: drawAll,
      bracket: bracketAll,
      timeline: timelineAll,
      impostor: impostorAll,
      reverseFact: reverseAll,
      wyr: creative.wyr,
      spectrum: creative.spectrum,
      splitRoom: creative.splitRoom,
      friendSortRoles: creative.friendSortRoles,
      crowdCall: creative.crowdCall,
    },
    null,
    2,
  )}\n`,
);
console.log(`Wrote ${OUT}`);
console.log(
  [
    `factCheck ${factCheck.length}`,
    `quiz ${quizAll.length}`,
    `draw ${drawAll.length}`,
    `bracket ${bracketAll.length}`,
    `timeline ${timelineAll.length}`,
    `impostor ${impostorAll.length} packs (${impostorAll.reduce((n, p) => n + p.items.length, 0)} items)`,
    `reverseFact ${reverseAll.length}`,
    `wyr ${creative.wyr.length}`,
    `spectrum ${creative.spectrum.length}`,
    `friendSortRoles ${creative.friendSortRoles.length}`,
    `crowdCall ${creative.crowdCall.length}`,
  ].join(", "),
);
